### ISSUE TITLE
Error: PhaserES6Webpack@1.2.1 deploy: `webpack --config webpack.production.config.js`

### ISSUE THREAD

**Issue by boas19910115** [lean/phaser-es6-webpack#77]
> **I run "npm run deploy". After the build dir created in root dir, the error occured.**

- 0 info it worked if it ends with ok
- 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
- 1 verbose cli   'C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
- 1 verbose cli   'run',
- 1 verbose cli   'deploy' ]
- 2 info using npm@6.4.0
- 3 info using node@v8.11.1
- 4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
- 5 info lifecycle PhaserES6Webpack@1.2.1~predeploy: PhaserES6Webpack@1.2.1
- 6 info lifecycle PhaserES6Webpack@1.2.1~deploy: PhaserES6Webpack@1.2.1
- 7 verbose lifecycle PhaserES6Webpack@1.2.1~deploy: unsafe-perm in lifecycle true
- 8 verbose lifecycle PhaserES6Webpack@1.2.1~deploy: PATH: C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\jonanwu\yuanbao-game\three-cards-phaser\node_modules\.bin;C:\jdk-8u171\bin\;C:\jdk-8u171\bin\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\apache-maven-3.5.3\bin\;;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Go\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\admin\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\admin\AppData\Roaming\npm;C:\Users\admin\AppData\Local\GitHubDesktop\bin;C:\Users\admin\AppData\Local\Microsoft\WindowsApps;C:\Users\admin\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin;C:\Users\admin\go\bin
- 9 verbose lifecycle PhaserES6Webpack@1.2.1~deploy: CWD: C:\jonanwu\yuanbao-game\three-cards-phaser
- 10 silly lifecycle PhaserES6Webpack@1.2.1~deploy: Args: [ '/d /s /c', 'webpack --config webpack.production.config.js' ]
- 11 silly lifecycle PhaserES6Webpack@1.2.1~deploy: Returned: code: 2  signal: null
- 12 info lifecycle PhaserES6Webpack@1.2.1~deploy: Failed to exec deploy script

> The error start from here

**### - 13 verbose stack Error: PhaserES6Webpack@1.2.1 deploy: `webpack --config webpack.production.config.js`**
- 13 verbose stack Exit status 2
- 13 verbose stack     at EventEmitter.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
- 13 verbose stack     at emitTwo (events.js:126:13)
- 13 verbose stack     at EventEmitter.emit (events.js:214:7)
- 13 verbose stack     at ChildProcess.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
- 13 verbose stack     at emitTwo (events.js:126:13)
- 13 verbose stack     at ChildProcess.emit (events.js:214:7)
- 13 verbose stack     at maybeClose (internal/child_process.js:925:16)
- 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
- 14 verbose pkgid PhaserES6Webpack@1.2.1
- 15 verbose cwd C:\jonanwu\yuanbao-game\three-cards-phaser
- 16 verbose Windows_NT 10.0.17134
- 17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "deploy"
- 18 verbose node v8.11.1
- 19 verbose npm  v6.4.0
- 20 error code ELIFECYCLE
- 21 error errno 2
- 22 error PhaserES6Webpack@1.2.1 deploy: `webpack --config webpack.production.config.js`
- 22 error Exit status 2
- 23 error Failed at the PhaserES6Webpack@1.2.1 deploy script.
- 23 error This is probably not a problem with npm. There is likely additional logging output above.
- 24 verbose exit [ 2, true ]
-

**Comment by boas19910115** [comment]
> > **I run "npm run deploy". After the build dir created in root dir, the error occured.**
> 
> * 0 info it worked if it ends with ok
> * 1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
> * 1 verbose cli   'C:\Users\admin\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js',
> * 1 verbose cli   'run',
> * 1 verbose cli   'deploy' ]
> * 2 info using npm@6.4.0
> * 3 info using node@v8.11.1
> * 4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
> * 5 info lifecycle PhaserES6Webpack@1.2.1~predeploy: PhaserES6Webpack@1.2.1
> * 6 info lifecycle PhaserES6Webpack@1.2.1~deploy: PhaserES6Webpack@1.2.1
> * 7 verbose lifecycle PhaserES6Webpack@1.2.1~deploy: unsafe-perm in lifecycle true
> * 8 verbose lifecycle PhaserES6Webpack@1.2.1~deploy: PATH: C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\jonanwu\yuanbao-game\three-cards-phaser\node_modules.bin;C:\jdk-8u171\bin;C:\jdk-8u171\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\apache-maven-3.5.3\bin;;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Microsoft VS Code\bin;C:\Go\bin;C:\Program Files\dotnet;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Users\admin\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\admin\AppData\Roaming\npm;C:\Users\admin\AppData\Local\GitHubDesktop\bin;C:\Users\admin\AppData\Local\Microsoft\WindowsApps;C:\Users\admin\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin;C:\Users\admin\go\bin
> * 9 verbose lifecycle PhaserES6Webpack@1.2.1~deploy: CWD: C:\jonanwu\yuanbao-game\three-cards-phaser
> * 10 silly lifecycle PhaserES6Webpack@1.2.1~deploy: Args: [ '/d /s /c', 'webpack --config webpack.production.config.js' ]
> * 11 silly lifecycle PhaserES6Webpack@1.2.1~deploy: Returned: code: 2  signal: null
> * 12 info lifecycle PhaserES6Webpack@1.2.1~deploy: Failed to exec deploy script
> 
> > The error start from here
> 
> **### - 13 verbose stack Error: PhaserES6Webpack@1.2.1 deploy: `webpack --config webpack.production.config.js`**
> 
> * 13 verbose stack Exit status 2
> * 13 verbose stack     at EventEmitter. (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
> * 13 verbose stack     at emitTwo (events.js:126:13)
> * 13 verbose stack     at EventEmitter.emit (events.js:214:7)
> * 13 verbose stack     at ChildProcess. (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
> * 13 verbose stack     at emitTwo (events.js:126:13)
> * 13 verbose stack     at ChildProcess.emit (events.js:214:7)
> * 13 verbose stack     at maybeClose (internal/child_process.js:925:16)
> * 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> * 14 verbose pkgid PhaserES6Webpack@1.2.1
> * 15 verbose cwd C:\jonanwu\yuanbao-game\three-cards-phaser
> * 16 verbose Windows_NT 10.0.17134
> * 17 verbose argv "C:\Program Files\nodejs\node.exe" "C:\Users\admin\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "run" "deploy"
> * 18 verbose node v8.11.1
> * 19 verbose npm  v6.4.0
> * 20 error code ELIFECYCLE
> * 21 error errno 2
> * 22 error PhaserES6Webpack@1.2.1 deploy: `webpack --config webpack.production.config.js`
> * 22 error Exit status 2
> * 23 error Failed at the PhaserES6Webpack@1.2.1 deploy script.
> * 23 error This is probably not a problem with npm. There is likely additional logging output above.
> * 24 verbose exit [ 2, true ]
